name: WebStore .NET 5

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c debug
      
    - name: Test
      run: dotnet test --no-build -c debug -v n
